# Generated by Django 3.0.6 on 2020-06-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0002_author_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='recipebox.RecipeModel'),
        ),
    ]
